mlflow:
  experiment:
    name: train_v1
    tags: 
      exec: prd  # dev, test, prd

out_dir: train_v1/prd001

option:
  train: true
  predict: true

feature_engineering:
  weight_cutoff: 0
  method_fillna: '-999'  # -999, forward
  cross: false

cv:
  name: 'nocv'
  param:
    n_splits: 1

model:
  name: XGBClassifier
  model_param:
    n_estimators: 500
    max_depth: 11
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.7
    missing: -999
    random_state: 2020
    tree_method: gpu_hist
  train_param:
    eval_metric: null
    early_stopping_rounds: null

target:
  path: processed/basic_v1/train.pkl
  col: action

info:
  path: processed/basic_v1/train.pkl
  cols:
    - date
    - weight
    - resp_1
    - resp_2
    - resp_3
    - resp_4
    - resp
    - ts_id

features:
  - name: raw
    path: processed/basic_v1/train.pkl
    cols:
      - feature_0
      - feature_1
      - feature_2
      - feature_3
      - feature_4
      - feature_5
      - feature_6
      - feature_7
      - feature_8
      - feature_9
      - feature_10
      - feature_11
      - feature_12
      - feature_13
      - feature_14
      - feature_15
      - feature_16
      - feature_17
      - feature_18
      - feature_19
      - feature_20
      - feature_21
      - feature_22
      - feature_23
      - feature_24
      - feature_25
      - feature_26
      - feature_27
      - feature_28
      - feature_29
      - feature_30
      - feature_31
      - feature_32
      - feature_33
      - feature_34
      - feature_35
      - feature_36
      - feature_37
      - feature_38
      - feature_39
      - feature_40
      - feature_41
      - feature_42
      - feature_43
      - feature_44
      - feature_45
      - feature_46
      - feature_47
      - feature_48
      - feature_49
      - feature_50
      - feature_51
      - feature_52
      - feature_53
      - feature_54
      - feature_55
      - feature_56
      - feature_57
      - feature_58
      - feature_59
      - feature_60
      - feature_61
      - feature_62
      - feature_63
      - feature_64
      - feature_65
      - feature_66
      - feature_67
      - feature_68
      - feature_69
      - feature_70
      - feature_71
      - feature_72
      - feature_73
      - feature_74
      - feature_75
      - feature_76
      - feature_77
      - feature_78
      - feature_79
      - feature_80
      - feature_81
      - feature_82
      - feature_83
      - feature_84
      - feature_85
      - feature_86
      - feature_87
      - feature_88
      - feature_89
      - feature_90
      - feature_91
      - feature_92
      - feature_93
      - feature_94
      - feature_95
      - feature_96
      - feature_97
      - feature_98
      - feature_99
      - feature_100
      - feature_101
      - feature_102
      - feature_103
      - feature_104
      - feature_105
      - feature_106
      - feature_107
      - feature_108
      - feature_109
      - feature_110
      - feature_111
      - feature_112
      - feature_113
      - feature_114
      - feature_115
      - feature_116
      - feature_117
      - feature_118
      - feature_119
      - feature_120
      - feature_121
      - feature_122
      - feature_123
      - feature_124
      - feature_125
      - feature_126
      - feature_127
      - feature_128
      - feature_129
